[template.environment]
  STYTCH_PROJECT_ENV = "test"
  STYTCH_PROJECT_ID = process.env.STYTCH_PROJECT_ID
  NEXT_PUBLIC_STYTCH_PUBLIC_TOKEN = process.env.STYTCH_PUBLIC_TOKEN
  STYTCH_SECRET = process.env.STYTCH_SECRET
